name: Auto Alert

on:
  schedule:
#ทำงานแล้ว    - cron: '*/5 * * * *'
  #workflow_dispatch:

jobs:
  notify-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Dynamic Greeting
        run: |
          echo "Hello "