name: Auto Delete Branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete Remote Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          echo "Deleting merged branch: $BRANCH_NAME"
          git push origin --delete "$BRANCH_NAME"